# Generated by Django 2.0.5 on 2018-06-01 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_addrs', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_state', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_city', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_addrs', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('documents_submitted', models.CharField(blank=True, max_length=100, null=True)),
                ('emerg_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emerg_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emerg_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('emerg_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='educational_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=100, null=True)),
                ('marks', models.IntegerField(blank=True)),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('add_skill', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='experience_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('leaving_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_sal', models.IntegerField(blank=True, null=True)),
                ('hra', models.IntegerField(blank=True)),
                ('conveyance', models.IntegerField(blank=True)),
                ('pf_employer', models.IntegerField(blank=True)),
                ('performance_allowance', models.IntegerField(blank=True)),
                ('arrears', models.IntegerField(blank=True)),
                ('others', models.IntegerField(blank=True)),
                ('incentives', models.IntegerField(blank=True)),
                ('total_earning', models.IntegerField(blank=True)),
                ('pf_employee', models.IntegerField(blank=True)),
                ('prof_tax', models.IntegerField(blank=True)),
                ('advance', models.IntegerField(blank=True)),
                ('IT_ded', models.IntegerField(blank=True)),
                ('total_ded', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personnel_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('altr_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('blood_grp', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
