# Generated by Django 2.0.5 on 2018-06-01 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user_extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_role', models.CharField(max_length=100)),
                ('is_designation', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('mobile_no', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
