# Generated by Django 2.0.5 on 2018-06-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0003_attendance_holidays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='emp_id',
            new_name='emp',
        ),
    ]
