# Generated by Django 2.0.5 on 2018-06-01 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrmsapp', '0005_auto_20180601_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_info',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='educational_info',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='experience_info',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='personnel_info',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='basic_info',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='educational_info',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='experience_info',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='personnel_info',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
