# Generated by Django 2.0.5 on 2018-06-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0006_auto_20180601_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel_info',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
