# Generated by Django 2.0.5 on 2018-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0008_auto_20180606_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_info',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educational_info',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
