# Generated by Django 2.0.5 on 2018-06-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0009_auto_20180606_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educational_info',
            name='add_skill',
        ),
        migrations.AddField(
            model_name='auth_user_extended',
            name='add_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
